[project]
name = "odoo-addons-oca-product-attribute"
version = "18.0.20241023.0"
dependencies = [
    "odoo-addon-product_dimension==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
